name: "ci-eds-r-notebooks"
run-name: "EDS R Notebook CI triggered by @${{ github.actor }}"

on:
  schedule:
    - cron: "0 5 * * *"

  push:
    branches-ignore:
      - "main"
    tags:
      - "v*.*.*"

jobs:
  eds-r-notebook-snapshot:
    if: ${{ github.ref != 'refs/heads/dev' && github.ref != 'refs/heads/main' && github.event_name == 'push' }}
    uses: "./.github/workflows/build-notebook.yml"
    with:
      dockerfile-path: &docker-path "eds-base-notebook/Dockerfile"
      image-name: &image-name  "ghcr.io/aphp/r-eds-notebook"
      image-custom-tag: "x86_64-ubuntu-24.04-snapshot"
      base-notebook-image: &base-notebook-image "quay.io/jupyter/base-notebook:x86_64-ubuntu-24.04"
      notebook-image: &notebook-image "EDS-R-NOTEBOOK"

  eds-r-notebook-dev:
    if: ${{ github.ref == 'refs/heads/dev' && github.event_name == 'push' }}
    uses: "./.github/workflows/build-notebook.yml"
    with:
      dockerfile-path: *docker-path 
      image-name: *image-name
      image-custom-tag: "x86_64-ubuntu-24.04-dev"
      base-notebook-image: *base-notebook-image
      notebook-image: *notebook-image


  eds-r-notebook-nightly:
    if: ${{ github.event_name == 'schedule' }}
    uses: "./.github/workflows/build-notebook.yml"
    with:
      dockerfile-path: *docker-path
      image-name: *image-name
      image-custom-tag: "x86_64-ubuntu-24.04"
      base-notebook-image: *base-notebook-image
      notebook-image: *notebook-image
